### ISSUE TITLE
"**1.**abc" Does not parse as bold.

### ISSUE THREAD

**Issue by rupertlssmith** [pablohirafuji/elm-markdown#8]
Parses as a Text block without the Emphasis inline.

`[Text "**1.**abc"]`

If a space is added after the . it works:

`[Emphasis 2 [Text "1."],Text " abc"]`

**Comment by pablohirafuji** [comment]
I followed the [commonmark specs](https://spec.commonmark.org/0.30/#example-352). You can try the same code [here](https://spec.commonmark.org/dingus/) and it will match the current behavior.

You can read the rationale behind this behavior [here](https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis).

**Comment by rupertlssmith** [comment]
Yeah, it does match the behaviour on https://spec.commonmark.org/dingus/.

What is strange is "\*\*1\*\*abc" puts the 1 in bold, but adding in the "." after the one breaks it. But I was never aware of "." being a special character in markdown so why does it affect things?

The example driven commonmark specs look really useful, so thanks for the link. I will check them and see if it explains why the "." behaves strangely.

**Comment by rupertlssmith** [comment]
**1.**abc

**1**abc

**1.** abc

Sorry - just me testing how github markdown handles it...

**Comment by rupertlssmith** [comment]
As a workaround, you can put a zero-width space after the closing emphasis delimiters:

\*\*1.\*\*\&\#8203;abc ---> **1.**&#8203;abc

**Comment by rupertlssmith** [comment]
I agree, its not a bug its correct implementation, so closing the issue and going with my workaround.

**Comment by rupertlssmith** [comment]
I agree, its not a bug its correct implementation, so closing the issue and going with my workaround.
